version: '3.4'

services:
  testtaskflask_app:
    container_name: testtaskflask_app
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env_file
    volumes:
      - ./app:/home/python/app
    # command: bash -c "flask db init && flask db migrate && flask db upgrade"
    command: bash -c "flask run -h 0.0.0.0 --no-debugger"
    links:
      - testtaskflask_db
    depends_on:
      - testtaskflask_db
    ports:
      - 5000:5000
    networks:
      - testtaskflask-api


  testtaskflask_db:
    container_name: testtaskflask_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_HOST=localhost
    image: postgres:latest
    restart: "on-failure"
    ports:
      - 5432:5432


networks:
  testtaskflask-api:
    name: testtaskflask-api
